Repository ouzi-dev/prow-helm-chart, pull requests merged in 2020-06, with the labels that each got.

#90 feat: Switch API version for deployments to work on K8s 1.16+
  prow/templates/crier-deployment.yaml
  prow/templates/deck-deployment.yaml
  prow/templates/ghproxy-deployment.yaml
  prow/templates/hook-deployment.yaml
  prow/templates/horologium-deployment.yaml
  prow/templates/needsrebase-deployment.yaml
  prow/templates/plank-deployment.yaml
  prow/templates/pushgateway-deployment.yaml
  prow/templates/pushgateway-proxy-deployment.yaml
  prow/templates/sinker-deployment.yaml
  prow/templates/statusreconsiler-deployment.yaml
  prow/templates/tide-deployment.yaml
Labels: approved, lgtm, ok-to-test, size/M

#92 feat: upgrade to prow v20200610 6c96a0a6ed
  prow/templates/branchprotector-cronjob.yaml
  prow/templates/crier-deployment.yaml
  prow/templates/deck-deployment.yaml
  prow/templates/hook-deployment.yaml
  prow/templates/needsrebase-deployment.yaml
  prow/templates/plank-deployment.yaml
  prow/templates/statusreconsiler-deployment.yaml
  prow/templates/tide-deployment.yaml
  prow/values.yaml
Labels: approved, lgtm, size/M

#93 fix: set correct app version
  prow/Chart.yaml
Labels: approved, lgtm, size/XS

#95 feat: push chart to chartmuseum
  .prow.yaml
  Makefile
  package.json
Labels: approved, lgtm, size/S

#96 docs: add steps to install via the ouzi helm repo
  README.md
Labels: approved, lgtm, size/S

#97 docs: fix bad whitespace formatting
  README.md
Labels: approved, lgtm, size/XS

#98 docs: final whitespace tweak
  README.md
Labels: approved, lgtm, size/M
