Repository ouzi-dev/prow-helm-chart, pull requests merged in 2020-04, with the labels that each got.

#79 feat: support tolerations
  .prow.yaml
  Makefile
  prow/templates/branchprotector-cronjob.yaml
  prow/templates/crier-deployment.yaml
  prow/templates/deck-deployment.yaml
  prow/templates/ghproxy-deployment.yaml
  prow/templates/hook-deployment.yaml
  prow/templates/horologium-deployment.yaml
  prow/templates/labelsync-cronjob.yaml
  prow/templates/needsrebase-deployment.yaml
  prow/templates/pipeline-deployemnt.yaml
  prow/templates/plank-deployment.yaml
  prow/templates/pushgateway-deployment.yaml
  prow/templates/pushgateway-proxy-deployment.yaml
  prow/templates/sinker-deployment.yaml
  prow/templates/statusreconsiler-deployment.yaml
  prow/templates/tide-deployment.yaml
  prow/values.yaml
Labels: approved, lgtm, size/L

#80 fix: update npm deps to latest version
  Makefile
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#84 feat: upgrade to prow v20200427-baaf248ed
  prow/templates/config-configmap.yaml
  prow/templates/crier-deployment.yaml
  prow/templates/crier-rbac.yaml
  prow/templates/deck-deployment.yaml
  prow/templates/hook-deployment.yaml
  prow/templates/hook-rbac.yaml
  prow/templates/needsrebase-deployment.yaml
  prow/templates/plank-deployment.yaml
  prow/templates/tide-deployment.yaml
  prow/values.yaml
Labels: approved, lgtm, size/M
